name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - master  # o 'master', segÃºn tu repo
      - develop
  workflow_dispatch:     # ðŸ‘ˆ AÃ±ade esta lÃ­nea para habilitar el botÃ³n manual

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # ðŸ‘‡ Asociamos el entorno GitHub segÃºn la rama
    environment: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod' }}

    env:
      NG_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      NG_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      NG_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      NG_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      NG_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      NG_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      NG_APP_THEMOVIEDB_API_KEY: ${{ secrets.THEMOVIEDB_API_KEY }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ðŸ‘ˆ Clona todo el historial (necesario para GitVersion)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Show calculated version
        run: echo "Version = ${{ steps.gitversion.outputs.SemVer }}"

      # ðŸ‘‡ Este paso genera environment.ts con la versiÃ³n incluida
      - name: Generate environment file
        run: node scripts/set-env.cjs "${{ steps.gitversion.outputs.SemVer }}"

      - name: Build Angular app
        run: npm run build --configuration=${{ github.ref == 'refs/heads/develop' && 'development' || 'production' }}

      - name: Show environment info
        run: |
          echo "Branch ref: ${{ github.ref }}"
          echo "Detected environment: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod' }}"

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.15.3
        with:
          args: deploy --only hosting -P ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod' }}
