name: Build and Release

on:
#  push:
#    branches:
#      - master
  workflow_dispatch: # EjecuciÃ³n manual

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ðŸ‘ˆ Clona todo el historial (necesario para GitVersion)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Show calculated version
        run: echo "Version = ${{ steps.gitversion.outputs.SemVer }}"

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Package build artifact
        run: |
          cd www
          zip -r ../app-dist.zip .
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: app-dist.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.gitversion.outputs.SemVer }}
          name: "Release v${{ steps.gitversion.outputs.SemVer }}"
          body: "ðŸš€ Nueva versiÃ³n generada automÃ¡ticamente"
          files: app-dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
